### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [iagof-dev/N3rdyKits#6]
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

https://github.com/iagof-dev/N3rdyKits/blob/a97069dfabb550d7c465c4b562a421455932197f/src/main/java/com/n3rdydev/events/handleWarpSelector.java#L35

**Comment by iago-fragnan** [comment]
Thank you for the tip, but in this case, the context of the plugin/server, the player will not be able to use an anvil... but it is a good tip for future projects.
